### ISSUE TITLE
Inconsistencies in the API functions

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/hardware-wallet-daemon#31]
Although most API functions have a similar behavior, there are small differences in some of them, which makes it a little harder to understand the API and could make the code needed to use the API more complicated. The inconsistencies that I found are:

- Most API functions accept data in the `application/json` format, but `/applySettings`, `/recovery`, `/generateMnemonic` and `/setMnemonic` use the `x-www-form-urlencoded` format.

- In some functions the names of the arguments are separated with hyphens (like `three-word-parameter`) while in others are separated with underscores (like `three_word_parameter`). I think the second format is better, because using hyphens may cause problems with some languajes.

- When the operation finishes successfully, some functions return the response directly inside the `data` property, while others add an additional property, like `data.signature`. I think the extra property is not necessary, especially because it is always one, but I do not know if there is any reason for it.

**Comment by therealssj** [comment]
- I just did it based on how I felt it should be like. @gz-c what do you think?

- the second point is a direct result of the first one. the functions using `x-www-form-urlencoded` format use hyphens instead of underscore

- The response sometimes contains an additional property to better identify what the response is but if the response is just a success message there is no point to add an additional property. 
The only place where i m not following that rule is for responses for `Intermediate` requests but I made it so to make it work with swagger for the time being till I found out a better solution.

**Comment by gz-c** [comment]
* Pick one content-type and use it, unless there is an exception (like multipart form data for image upload, that doesn't belong in json). Use JSON

* Some args are hyphenated, some args are underscored, but endpoint names are camel case?  Should be consistent

* Should also be consistent. I prefer not having the extra nesting inside of `"data"`.

> sometimes contains an additional property to better identify what the response is 
This is inferred by the endpoint, which should always return 1 data type. The documentation can explain what the data type is for a given endpoint.
