### ISSUE TITLE
Figure out release steps

### ISSUE THREAD

**Issue by therealssj** [skycoin/hardware-wallet-daemon#40]
- What needs to be done for the release?

**Comment by therealssj** [comment]
These are the options:
https://github.com/skycoin/hardware-wallet-daemon/wiki/Daemon-packaging

we decided to go with route 7

**Comment by gz-c** [comment]
- This release needs to have semver tagged release versions
- We don't need to package this with route 7 (which is why we chose route 7)
- The skycoin release build process will need modification to optionally build and include the hw daemon in the release package
- But first, route 7 should be implemented in the skycoin daemon
