### ISSUE TITLE
Endpoint for removing pin code

### ISSUE THREAD

**Issue by therealssj** [skycoin/hardware-wallet-daemon#50]
Currently `/set_pin_code` can only change the pin code and not remove it as I have set `removePin` param of `ChangePin` function to false
https://github.com/skycoin/hardware-wallet-daemon/blob/30c77800b12a677034f70f66dedd9da143af600f/src/api/set_pin_code.go#L40

Should we have a separate endpoint for removing pin like `/remove_pin_code` or convert `set_pin_code` to generic endpoint?

@Senyoret1 thoughts?

**Comment by Senyoret1** [comment]
Maybe creating a new function would be more natural, because the name `set_pin_code` does not sounds like the function for removing the pin, but you can take that as me just trying to find something to say :smile:. In fact, I have no any strong preference between creating a new function or adding a new parameter to the existing one, both approaches can work
